[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
test = "contracts/test"
cache_path = "cache_forge"
via_ir = true

[rpc_endpoints]
base = "https://mainnet.base.org"

[profile.ci]
fuzz = { runs = 10000 }
