
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
via_ir = true
solc = "0.8.20"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
