
[profile.default]
src = 'contracts/src'
out = 'out'
libs = ['node_modules', 'lib']
via_ir = true
optimizer_runs = 1000000

[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/_rq09Uz--vhSNI9x6BGOb"

[etherscan]
base_sepolia = { key = "", url = "https://api-sepolia.basescan.org/api" }
